version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://localhost:27017/nestjs_test
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
